import { useState, type FormEvent } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { supabase } from '../lib/supabase';

const projectTypes = ['DIGITAL PLATFORM', 'E-COMMERCE', 'BRAND IDENTITY', 'CREATIVE DEVELOPMENT'];
const timelines = ['ASAP', '2–4 WEEKS', '1–2 MONTHS', 'FLEXIBLE'];

export default function Contact() {
  const [step,setStep]=useState(1); const [projectType,setProjectType]=useState(''); const [timeline,setTimeline]=useState(''); const [details,setDetails]=useState(''); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [submitted,setSubmitted]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const canContinue=step===1?!!projectType:step===2?!!timeline:!!details.trim();
  const next=()=>{if(!canContinue)return;setStep(current=>Math.min(current+1,4));if(step===1&&supabase)supabase.from('analytics_events').insert({event_name:'contact_started',path:window.location.pathname});};
  const back=()=>setStep(current=>Math.max(current-1,1));
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!name.trim()||!email.trim()||!email.includes('@')){setError('Please enter a valid name and email.');return;}setBusy(true);setError('');
    if(supabase){const {error:insertError}=await supabase.from('inquiries').insert({name:name.trim(),email:email.trim(),project_type:projectType,timeline,details:details.trim()});if(insertError){setError('We could not save your inquiry. Please try again.');setBusy(false);return;}await supabase.from('analytics_events').insert({event_name:'inquiry_submitted',path:window.location.pathname});setSubmitted(true);setBusy(false);return;}
    const subject=`Project Inquiry: ${projectType}`;const body=[`Project type: ${projectType}`,`Timeline: ${timeline}`,`Project details: ${details}`,`Name: ${name}`,`Email: ${email}`].join('\n\n');setSubmitted(true);setBusy(false);window.setTimeout(()=>{window.location.href=`mailto:yunusfawzan9@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;},350);
  };
  if(submitted)return <section id="contact" className="relative overflow-hidden bg-aer-black px-6 py-20 md:px-12 md:py-28"><div className="mx-auto flex min-h-[55vh] max-w-4xl flex-col items-center justify-center text-center"><p className="mb-5 text-[9px] tracking-[0.32em] text-aer-blue">INQUIRY RECEIVED</p><h2 className="font-editorial text-6xl uppercase leading-[0.86] tracking-[-0.035em] md:text-8xl">Let&apos;s build<br/><span className="italic text-aer-cream/55">what comes next.</span></h2><p className="mt-7 max-w-md text-[10px] leading-6 tracking-[0.08em] text-aer-cream/35">Your project is in the studio inbox. We&apos;ll review the brief and follow up using the details you provided.</p></div></section>;
  return <section id="contact" className="relative overflow-hidden bg-aer-black px-6 py-20 md:px-12 md:py-28"><div className="mx-auto max-w-4xl"><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-15% 0px'}} transition={{duration:.7,ease:[.21,.47,.32,.98]}} className="text-center"><p className="mb-5 text-[9px] tracking-[0.32em] text-aer-blue">START A PROJECT</p><h2 className="font-editorial text-6xl uppercase leading-[0.86] tracking-[-0.035em] md:text-8xl">Let&apos;s build<br/><span className="italic text-aer-cream/55">what comes next.</span></h2><p className="mx-auto mt-6 max-w-md text-[10px] leading-6 tracking-[0.08em] text-aer-cream/35">A few questions. A clear direction. Then we build.</p></motion.div><motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-10% 0px'}} transition={{duration:.7,delay:.08,ease:[.21,.47,.32,.98]}} className="mx-auto mt-12 max-w-2xl md:mt-14"><div className="mb-7 flex items-center justify-between border-b border-aer-cream/10 pb-4"><div className="flex items-center gap-4"><span className="text-[9px] tracking-[0.22em] text-aer-blue">INITIATE</span><span className="text-[8px] tracking-[0.16em] text-aer-cream/20">PROJECT INQUIRY</span></div><span className="text-[9px] tracking-[0.18em] text-aer-cream/25" aria-live="polite">0{step} / 04</span></div><form onSubmit={submit} noValidate><div className="min-h-[300px]"><AnimatePresence mode="wait">
  {step===1&&<motion.div key="1" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}} transition={{duration:.25}}><p className="mb-5 text-[9px] tracking-[0.2em] text-aer-cream/30">01 — WHAT ARE WE MAKING?</p><div className="border-t border-aer-cream/10" role="group" aria-label="Project type">{projectTypes.map((item,index)=>{const selected=projectType===item;return <button key={item} type="button" aria-pressed={selected} onClick={()=>setProjectType(item)} className="group relative flex w-full items-center justify-between border-b border-aer-cream/10 py-5 text-left focus-visible:outline focus-visible:outline-1 focus-visible:outline-aer-blue md:py-6"><span className={`font-editorial text-xl uppercase leading-none md:text-2xl ${selected?'italic text-aer-blue':'text-aer-cream/60 group-hover:text-aer-cream'}`}>{item}</span><span className={`text-[8px] tracking-[0.18em] ${selected?'text-aer-blue':'text-aer-cream/20'}`}>0{index+1}</span>{selected&&<motion.span layoutId="project-selection" className="absolute bottom-[-1px] left-0 h-px w-full bg-aer-blue"/>}</button>})}</div></motion.div>}
  {step===2&&<motion.div key="2" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}} transition={{duration:.25}}><p className="mb-5 text-[9px] tracking-[0.2em] text-aer-cream/30">02 — WHEN ARE YOU LOOKING TO MOVE?</p><div className="border-t border-aer-cream/10" role="group" aria-label="Project timeline">{timelines.map((item,index)=>{const selected=timeline===item;return <button key={item} type="button" aria-pressed={selected} onClick={()=>setTimeline(item)} className="group relative flex w-full items-center justify-between border-b border-aer-cream/10 py-6 text-left focus-visible:outline focus-visible:outline-1 focus-visible:outline-aer-blue"><span className={`font-editorial text-2xl uppercase ${selected?'italic text-aer-blue':'text-aer-cream/60 group-hover:text-aer-cream'}`}>{item}</span><span className={`text-[8px] tracking-[0.18em] ${selected?'text-aer-blue':'text-aer-cream/20'}`}>0{index+1}</span>{selected&&<motion.span layoutId="timeline-selection" className="absolute bottom-[-1px] left-0 h-px w-full bg-aer-blue"/>}</button>})}</div></motion.div>}
  {step===3&&<motion.div key="3" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}} transition={{duration:.25}}><label htmlFor="project-details" className="mb-5 block text-[9px] tracking-[0.2em] text-aer-cream/30">03 — TELL US ABOUT IT</label><textarea id="project-details" required value={details} onChange={e=>setDetails(e.target.value)} placeholder="What are you building? What should the website achieve? Anything useful to know." rows={7} className="w-full resize-none border-b border-aer-cream/15 bg-transparent py-4 text-[12px] leading-6 tracking-[0.04em] text-aer-cream outline-none placeholder:text-aer-cream/20 focus:border-aer-blue"/></motion.div>}
  {step===4&&<motion.div key="4" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}} transition={{duration:.25}}><p className="mb-5 text-[9px] tracking-[0.2em] text-aer-cream/30">04 — WHERE SHOULD WE REACH YOU?</p><div className="border-t border-aer-cream/10"><label htmlFor="contact-name" className="sr-only">Your name</label><input id="contact-name" required value={name} onChange={e=>setName(e.target.value)} placeholder="YOUR NAME" autoComplete="name" className="w-full border-b border-aer-cream/10 bg-transparent py-5 text-[11px] tracking-[0.14em] text-aer-cream outline-none placeholder:text-aer-cream/20 focus:border-aer-blue"/><label htmlFor="contact-email" className="sr-only">Your email</label><input id="contact-email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="YOUR EMAIL" autoComplete="email" className="w-full border-b border-aer-cream/10 bg-transparent py-5 text-[11px] tracking-[0.14em] text-aer-cream outline-none placeholder:text-aer-cream/20 focus:border-aer-blue"/></div><p className="mt-5 text-[9px] leading-5 tracking-[0.08em] text-aer-cream/25">Your inquiry is securely saved to the studio inbox when the production database is connected.</p></motion.div>}
</AnimatePresence></div>{error&&<p role="alert" className="mt-5 text-center text-[10px] text-red-200/80">{error}</p>}<div className="mt-8 flex flex-col items-center border-t border-aer-cream/10 pt-7">{step<4?<button type="button" onClick={next} disabled={!canContinue} className="group inline-flex min-w-[180px] items-center justify-center rounded-full border border-aer-cream/20 px-8 py-4 text-[9px] font-semibold uppercase tracking-[0.2em] text-aer-cream transition-all hover:border-aer-blue hover:bg-aer-blue hover:text-aer-charcoal disabled:pointer-events-none disabled:opacity-20"><span>Continue</span><span className="ml-2 transition-transform group-hover:translate-x-1">→</span></button>:<button type="submit" disabled={busy||!name.trim()||!email.trim()} className="group inline-flex min-w-[180px] items-center justify-center rounded-full border border-aer-cream/20 px-8 py-4 text-[9px] font-semibold uppercase tracking-[0.2em] text-aer-cream transition-all hover:border-aer-blue hover:bg-aer-blue hover:text-aer-charcoal disabled:pointer-events-none disabled:opacity-20"><span>{busy?'Sending…':'Send inquiry'}</span><span className="ml-2">↗</span></button>}{step>1&&<button type="button" onClick={back} className="mt-5 text-[9px] uppercase tracking-[0.22em] text-aer-cream/25 hover:text-aer-cream focus-visible:outline focus-visible:outline-1 focus-visible:outline-aer-blue">← Back</button>}</div></form></motion.div><div className="mt-16 flex items-end justify-between border-t border-aer-cream/10 pt-5 text-[8px] uppercase tracking-[0.2em] text-aer-cream/20 md:mt-20"><span>AER × VÆLOR</span><span>BUILD SOMETHING WORTH VISITING.</span></div></div></section>;
}
