import { useRef, type MouseEvent } from 'react';
import { motion, useMotionValue, useReducedMotion, useScroll, useSpring, useTransform } from 'framer-motion';

type WorkItem = { id: string; title: string; category: string; description: string; type: 'glass' | 'editorial' | 'spatial' | 'kinetic' };

const workItems: WorkItem[] = [
  { id: '01', title: 'DIGITAL COMMERCE', category: 'CONVERSION / SYSTEMS', description: 'A considered commerce direction where product, hierarchy, and interaction work as one clear system.', type: 'glass' },
  { id: '02', title: 'EDITORIAL PLATFORM', category: 'STORY / EXPERIENCE', description: 'A narrative-led interface built around typography, pacing, and enough space for content to breathe.', type: 'editorial' },
  { id: '03', title: 'SPATIAL INTERFACE', category: 'PRODUCT / INTERACTION', description: 'A depth-aware interface exploration using layered surfaces to make complex information feel tangible.', type: 'spatial' },
  { id: '04', title: 'KINETIC IDENTITY', category: 'BRAND / MOTION', description: 'A motion-led identity direction where typography becomes the primary expressive element of the interface.', type: 'kinetic' },
];

function StyleDemo({ type }: { type: WorkItem['type'] }) {
  if (type === 'glass') return <div className="relative flex h-full w-full items-center justify-center overflow-hidden bg-gradient-to-br from-aer-charcoal via-[#1a2a3a] to-aer-charcoal p-8"><div className="absolute left-1/4 top-1/4 h-40 w-40 rounded-full bg-aer-blue/20 blur-3xl"/><div className="absolute bottom-1/4 right-1/4 h-48 w-48 rounded-full bg-purple-500/15 blur-3xl"/><div className="relative flex aspect-[4/3] w-full max-w-sm flex-col justify-between rounded-2xl border border-white/10 bg-white/5 p-6 shadow-2xl backdrop-blur-xl"><div className="flex justify-between"><div className="h-8 w-8 rounded-full bg-white/20"/><div className="h-2 w-16 rounded-full bg-white/20"/></div><div className="space-y-3"><div className="h-3 w-full rounded-full bg-white/20"/><div className="h-3 w-2/3 rounded-full bg-white/10"/></div></div></div>;
  if (type === 'editorial') return <div className="relative flex h-full w-full flex-col justify-between border border-aer-cream/10 bg-aer-charcoal p-8"><div className="flex justify-between"><span className="font-editorial text-xl italic text-aer-cream/60">Vol. IV</span><span className="w-24 text-right text-[8px] uppercase tracking-[0.2em] text-aer-cream/40">Curated Digital Experience</span></div><div className="border-t border-aer-cream/20 pt-6"><h3 className="font-editorial text-5xl uppercase leading-tight text-aer-cream md:text-6xl">The Art of<br/>Restraint</h3></div></div>;
  if (type === 'spatial') return <div className="perspective-[1000px] relative flex h-full w-full items-center justify-center overflow-hidden bg-[#0a0a0a]"><div className="absolute h-48 w-48 rotate-x-45 rotate-z-45 border border-aer-cream/20"/><div className="absolute h-48 w-48 rotate-x-45 rotate-z-45 border border-aer-blue/40 bg-aer-blue/5"/><div className="absolute flex h-48 w-48 rotate-x-45 rotate-z-45 items-center justify-center border border-aer-cream/60 bg-aer-cream/5"><span className="-rotate-45 font-mono text-xs tracking-widest text-aer-cream">Z-AXIS</span></div></div>;
  return <div className="relative flex h-full w-full items-center justify-center overflow-hidden bg-aer-blue"><div className="-rotate-12 scale-125"><h3 className="whitespace-nowrap font-editorial text-7xl uppercase leading-none text-aer-charcoal md:text-8xl">MOTION</h3><h3 className="whitespace-nowrap font-editorial text-7xl uppercase leading-none text-transparent md:text-8xl" style={{ WebkitTextStroke: '1.5px #0a0a0a' }}>MOTION</h3><h3 className="whitespace-nowrap font-editorial text-7xl uppercase leading-none text-aer-charcoal md:text-8xl">MOTION</h3></div></div>;
}

function WorkCard({ item, index }: { item: WorkItem; index: number }) {
  const ref = useRef<HTMLDivElement>(null);
  const reducedMotion = useReducedMotion();
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'end start'] });
  const parallaxY = useTransform(scrollYProgress, [0, 1], reducedMotion ? ['0%', '0%'] : ['-3%', '3%']);
  const mouseX = useMotionValue(0); const mouseY = useMotionValue(0);
  const spring = { damping: 24, stiffness: 180, mass: 1 };
  const rotateX = useSpring(useTransform(mouseY, [-0.5, 0.5], ['3deg', '-3deg']), spring);
  const rotateY = useSpring(useTransform(mouseX, [-0.5, 0.5], ['-3deg', '3deg']), spring);
  const even = index % 2 === 0;
  const handleMouseMove = (event: MouseEvent<HTMLDivElement>) => { if (reducedMotion) return; const r = event.currentTarget.getBoundingClientRect(); mouseX.set((event.clientX-r.left)/r.width-0.5); mouseY.set((event.clientY-r.top)/r.height-0.5); };
  return <article ref={ref} className="relative py-8 md:py-12"><div className="mb-5 flex items-center justify-between border-b border-aer-cream/10 pb-3 text-[8px] uppercase tracking-[0.24em] text-aer-cream/25"><span>SELECTED / {item.id}</span><span>{item.category}</span></div><div className={`flex flex-col items-center gap-8 md:gap-12 ${even ? 'md:flex-row' : 'md:flex-row-reverse'}`}><motion.div style={{ y: parallaxY, rotateX, rotateY, transformPerspective: 1000 }} onMouseMove={handleMouseMove} onMouseLeave={() => { mouseX.set(0); mouseY.set(0); }} className="group relative aspect-[4/5] w-full overflow-hidden border border-aer-cream/10 bg-aer-black md:aspect-[16/10] md:w-2/3"><motion.div initial={reducedMotion ? { opacity: 0 } : { scaleY: 1 }} whileInView={reducedMotion ? { opacity: 0 } : { scaleY: 0 }} viewport={{ once: true, margin: '-10%' }} transition={{ duration: reducedMotion ? 0 : 1 }} className="absolute inset-0 z-20 origin-top bg-aer-charcoal"/><StyleDemo type={item.type}/><div className="pointer-events-none absolute inset-0 z-10 border border-transparent transition-colors duration-500 group-hover:border-aer-blue/30"/></motion.div><div className={`w-full md:w-1/3 ${even ? 'text-left' : 'text-left md:text-right'}`}><p className="mb-4 text-[9px] tracking-[0.24em] text-aer-blue">{item.id}</p><h3 className="font-editorial text-4xl uppercase leading-[0.9] tracking-[-0.02em] text-aer-cream md:text-5xl lg:text-6xl">{item.title}</h3><p className={`mt-5 max-w-xs text-[10px] leading-6 tracking-[0.08em] text-aer-cream/40 ${even ? '' : 'md:ml-auto'}`}>{item.description}</p></div></div></article>;
}

export default function Work() {
  return <section id="work" className="relative w-full bg-aer-charcoal px-6 py-24 md:px-12 md:py-32"><div className="mx-auto max-w-7xl"><div className="mb-8 flex items-end justify-between border-b border-aer-cream/10 pb-5 md:mb-12"><div><p className="mb-3 text-[9px] tracking-[0.28em] text-aer-blue">SELECTED WORK</p><h2 className="font-editorial text-5xl uppercase leading-none tracking-[-0.025em] text-aer-cream md:text-7xl">Work that<br/><span className="italic text-aer-cream/45">earns attention.</span></h2></div><p className="hidden max-w-[180px] text-right text-[8px] uppercase leading-5 tracking-[0.18em] text-aer-cream/25 md:block">A small selection of concepts, systems, and digital directions.</p></div><div className="divide-y divide-aer-cream/10">{workItems.map((item,index)=><WorkCard key={item.id} item={item} index={index}/>)}</div><div className="mt-8 flex items-center justify-between border-t border-aer-cream/10 pt-5 text-[8px] uppercase tracking-[0.2em] text-aer-cream/20"><span>04 SELECTED DIRECTIONS</span><span>AER × VÆLOR</span></div></div></section>;
}
